- name: Flush handlers
  meta: flush_handlers

- name: Check website status
  uri:
    url: https://{{ website }}fd.jon-polansky.com
    status_code: 200
  register: result
  failed_when: false

- debug:
    msg: "The website is up and running."
  when: result == 200

- debug:
    msg: "The website is down. Restarting uWSGI."
  when: result.failed

- name: Website failed
  include_tasks: retry_tasks.yml
  until: result is defined and result.status == 200
  retries: 3
  delay: 5
  when: result.failed

- debug:
    msg: "Failed to bring the website up. Server rebooting."
  when: retry_count == 3

- name: Reboot server
  command: reboot
  when: retry_count == 3 and result is undefined or result.status != 200