- name: Flush handlers
  meta: flush_handlers

- name: Check website status
  uri:
    url: https://{{ website }}fd.jon-polansky.com
    status_code: 200
  register: result
  failed_when: false

- debug:
    msg: "The website is up and running."
  when: result == 200

- debug:
    msg: "The website is down. Restarting uWSGI."
  when: result.failed

- name: Restart uWSGI
  service:
    name: flaskapp
    state: restarted
  when: result.failed

- name: Check website status
  uri:
    url: https://{{ website }}fd.jon-polansky.com
    status_code: 200
  register: result
  failed_when: false

- debug:
    msg: "The restart did not bring the website back up. Rebooting the server."
  when: result.failed

- name: Reboot the server
  command: reboot
  when: result.failed