- name: Install nfs
  apt:
    name: nfs-common
    state: present

- name: Mount NFS share
  mount:
    name: /mnt/nfs
    src: "192.168.69.240:/mnt/Data/resume-db"
    fstype: nfs
    opts: defaults
    state: mounted
  notify:
    - Set permissions on mount point
    - Set permissions on logs folder