- name: Set frontend folder permissions
  file:
    path: /srv/frontend
    recurse: yes
    mode: "0770"
    owner: www-data
    group: www-data

- name: Set resume permissions
  file:
    path: /srv/frontend/static/JonathanPolanskyResume.docx
    mode: "u+r"
    owner: www-data
    group: www-data