- name: Copy frontend files
  copy:
    src: /var/lib/jenkins/workspace/{{ workspace_path }}/frontend/
    dest: /srv/frontend/
    force: true
  notify:
    - Set frontend folder permissions
    - Set resume permissions

- name: Copy flaskapp.service
  copy:
    src: /var/lib/jenkins/workspace/{{ workspace_path }}/backend/flaskapp.service
    dest: /etc/systemd/system
    force: true
  notify:
    - Reload systemctl daemon

- name: Copy disable-transparent-huge-pages.service
  copy:
    src: /var/lib/jenkins/workspace/{{ workspace_path }}/backend/disable-transparent-huge-pages.service
    dest: /etc/systemd/system
    force: true
  notify:
    - Reload systemctl daemon

- name: Enable disable-transparent-huge-pages.service
  service:
    name: disable-transparent-huge-pages
    state: started
    enabled: true

- name: Copy logrotate configuration
  copy:
    src: /var/lib/jenkins/workspace/{{ workspace_path }}/backend/uwsgi-logrotate-{{ logs_path }}
    dest: /etc/logrotate.d/
    force: true