- name: Configure webserver
  hosts: webservers
  remote_user: root
  become: yes
  become_method: sudo

  tasks:

    - name: Upgrade packages
      apt:
        update_cache: true
        upgrade: yes
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

    - name: Update OS
      apt:
        upgrade: dist
  
    - name: Copy frontend files
      copy:
        src: /var/lib/jenkins/workspace/{{ workspace_path }}/frontend/
        dest: /srv/frontend/
        force: true

    - name: Rename flask app (dev or prod)
      copy:
        src: /srv/frontend/{{ flaskapp }}
        dest: /srv/frontend/app.py
        remote_src: true
        force: true

    - name: Set frontend folder permissions
      file:
        path: /srv/frontend
        recurse: yes
        mode: "0770"
        owner: www-data
        group: www-data

    - name: Set resume permissions
      file:
        path: /srv/frontend/static/JonathanPolanskyResume.docx
        mode: "u+r"
        owner: www-data
        group: www-data

    - name: Copy flaskapp.service
      copy:
        src: /var/lib/jenkins/workspace/Resume/backend/flaskapp.service
        dest: /etc/systemd/system
        force: true

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Install uwsgi
      pip:
        name: uwsgi
        state: present

    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: present

    - name: Mount NFS share
      mount:
        name: /mnt/nfs
        src: "192.168.69.200:/volume1/resume-db"
        fstype: nfs
        opts: defaults
        state: mounted
      notify:
        - Set permissions on mount point
        - Set permissions on database
        
    - name: Install redis
      apt:
        name: redis-server
        state: present
      
    - name: Install redis python module  
      pip:
        name: redis
        state: present
      notify:
        - Redis - configure kernel
        - Redis - overcommit memory

    - name: Run flaskapp service
      service:
        name: flaskapp
        state: restarted
        enabled: true

    - name: Reload systemctl daemon
      command:
        cmd: systemctl daemon-reload

  handlers:
    - name: Set permissions on mount point
      file:
        path: /mnt/nfs
        state: directory
        owner: www-data
        group: www-data
        mode: "0770"

    - name: Set permissions on database
      file:
        path: /mnt/nfs/{{ database_name }}.db
        owner: www-data
        group: www-data
        mode: "0770"

    - name: Redis - configure kernel
      shell:
        cmd: echo never > /sys/kernel/mm/transparent_hugepage/enabled
        
    - name: Redis - overcommit memory
      shell:
        cmd: echo vm.overcommit_memory = 1 > /etc/sysctl.conf