- name: Configure webserver
  hosts: webservers
  remote_user: root
  become: yes
  become_method: sudo

  tasks:
  
    - name: Upgrade packages
      apt:
        update_cache: true
        upgrade: yes
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
  
    - name: Copy frontend files
      copy:
        src: /var/lib/jenkins/workspace/Resume/frontend/
        dest: /srv/frontend/
        force: true

    - name: Set frontend folder permissions
      file:
        path: /srv/frontend
        recurse: yes
        mode: "0770"
        owner: www-data
        group: www-data

    - name: Set resume permissions
      file:
        path: /srv/frontend/static/JonathanPolanskyResume.docx
        mode: "u+r"
        owner: www-data
        group: www-data

    #- name: Copy nginx.conf
    #  copy:
    #    src: /var/lib/jenkins/workspace/Resume/backend/nginx.conf
    #    dest: /etc/nginx
    #    force: true

    - name: Copy flaskapp.service
      copy:
        src: /var/lib/jenkins/workspace/Resume/backend/flaskapp.service
        dest: /etc/systemd/system
        force: true

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Install uwsgi
      pip:
        name: uwsgi
        state: present

    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: present

    - name: Mount NFS share
      mount:
        name: /mnt/nfs
        src: "192.168.69.200:/volume1/resume-db"
        fstype: nfs
        opts: defaults
        state: mounted
      notify:
        - Set permissions on mount point
        - Set permissions on database

    #- name: Install certbot
    #  community.general.snap:
    #    name: certbot
    #    state: present
    #    classic: true

    #- name: Run certbot
    #  command: certbot --nginx -d resume-dev.jon-polansky.com -n --agree-tos -q --email jon@jon-polansky.com
    #  register: certbot_output
    #  ignore_errors: yes

    #- name: Show Certbot Output
    #  debug:
    #    var: certbot_output

    #- name: Add Certbot Renewal Cron Job
    #  cron:
    #    name: "Renew SSL Certificates with Certbot"
    #    minute: "0"
    #    hour: "*/12"
    #    job: "certbot renew --quiet"

    - name: Run flaskapp service
      service:
        name: flaskapp
        state: restarted
        enabled: true

    - name: Reload systemctl daemon
      command:
        cmd: systemctl daemon-reload

    #- name: Reload nginx
    #  service:
    #    name: nginx
    #    state: reloaded
    #    enabled: true

  handlers:
    - name: Set permissions on mount point
      file:
        path: /mnt/nfs
        state: directory
        owner: www-data
        group: www-data
        mode: "0770"

    - name: Set permissions on database
      file:
        path: /mnt/nfs/visitors.db
        owner: www-data
        group: www-data
        mode: "0770"

