- name: Deploy files to webserver
  hosts: webservers
  remote_user: root
  become: yes
  become_method: sudo

  tasks:
    - name: Copy frontend files
      copy:
        src: /var/lib/jenkins/workspace/Resume/frontend/
        dest: /var/www/html/frontend/
        force: true

    - name: Copy nginx.conf
      copy:
        src: /var/lib/jenkins/workspace/Resume/backend/nginx.conf
        dest: /etc/nginx
        force: true

    -name: Reload nginx
      command:
        cmd: nginx -t
