- name: Test website connection
  hosts: webservers
  remote_user: root
  become: yes
  become_method: sudo

  tasks:
    - name: Check website status
      uri:
        url: https://{{ website }}.jon-polansky.com
        status_code: 200
      register: result
      ignore_errors: yes

    - name: Restart uWSGI
      service:
        name: flaskapp
        state: restarted
      when: result.failed